name: Health check

on:
  schedule:
    - cron: '*/10 * * * *'


jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v2
        with:
          url: https://pokedex-fso-veggie.herokuapp.com/health